name: Use the Composite Action with Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Do anything elsee
        run: echo Pretend to do other things 

      # Uses the Composite Action
      - name: Build and Push the image
        uses: lgf4591/DockerImageBuilderAction@main
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_PASSWORD}}
          image_name: alpine
          tag: $GITHUB_RUN_NUMBER
