name: Hello world

# on: [push]

on:
  push:
    branches: ["none"]
  pull_request:
    branches: ["none"]
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      # git clone git@github.com:lgf4591/codespaces-actions-playground.git
      - name: Checkout repo With SSH
        uses: lgf4591/CheckoutWithSSHAction@main
        with:
          repo_name: codespaces-actions-playground
          repo_owner: lgf4591
          git_private_key: ${{ secrets.ACTION_KEY }}
          shell: sh
          branch: main

      - name: Hello world
        run: |
          pwd
          ls -la
          echo "Hello world"
          echo "${{ github.repository_owner }}"
          echo "${{ github.repository }}"
          echo "${{ github.actor }}"
          echo "${{ runner.os }}"
        
      - name: Update Git With SSH
        uses: lgf4591/GitUpdateWithSSHAction@main
        # with:
        #   shell: bash
        #   branch: main
        #   commit: "hello"
      - uses: docker/build-push-action@v5
  
  stage1:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: create hello.txt
        run: |
          echo "hello" > hello.txt
          ls
      - uses: actions/upload-artifact@v2
        with:
          name: codespaces-actions-playground
          path: ./
  
  stage2:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: stage1
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: codespaces-actions-playground
          path: ./
      - name: create hello1.txt
        run: |
          pwd
          echo "hello1" > hello1.txt
          ls -la
