name: Hello world

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          echo "Hello world"
  
  stage1:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: create hello.txt
        run: |
          echo "hello" > hello.txt
          ls
  
  stage2:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: stage1
    steps:
      - name: create hello1.txt
        run: |
          echo "hello1" > hello1.txt
          ls -la
