name: Hello world

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          echo "Hello world"
  
  stage1:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: create hello.txt
        run: |
          echo "hello" > hello.txt
          ls
      - uses: actions/upload-artifact@v2
        with:
          name: codespaces-actions-playground
          path: ./
  
  stage2:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: stage1
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: codespaces-actions-playground
          path: ./
      - name: create hello1.txt
        run: |
          pwd
          cd ./codespaces-actions-playground
          echo "hello1" > hello1.txt
          ls -la
