name: Test Checkout Action

on:
  push:
    branches: ["none"]
  pull_request:
    branches: ["none"]
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with SSH
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: test
        run: |
          echo ls -la
          git branch -a
          git tag
          echo `date` >> demo.txt
      # - name: auto commit
      #   run: |
      #     git config --local user.email "lgf4591@outlook.com"
      #     git config --local user.name "github-action"
      #     git remote set-url origin https://${{ github.actor }}:${{ secrets.ACTION_TOKEN }}@github.com/${{ github.repository }}
      #     git add .
      #     git commit --allow-empty -m "auto commit by github actions"
      #     git push
      - name: auto commit
        uses: GitUpdateWithSSHAction@main

