
name: Test

# on: [push]

on:
  push:
    branches: ["none"]
  pull_request:
    branches: ["none"]
  workflow_dispatch:

jobs:
  stage3:
    runs-on: windows-latest
    steps:
      - name: hello-world
        run: |
          echo "${{ github.repository_owner }}"
          echo "${{ github.repository }}"
          echo "${{ github.actor }}"
          echo "${{ runner.os }}"
          Write-Output "$profile"
          New-Item -Path $env:USERPROFILE\.ssh -ItemType Directory -Force -ErrorAction SilentlyContinue
          Write-Output "${{ secrets.ACTION_KEY }}" > $env:USERPROFILE\.ssh\id_rsa
          cat $env:USERPROFILE\.ssh\id_rsa
          ssh-keyscan github.com >>  $env:USERPROFILE\.ssh\known_hosts
          cat $env:USERPROFILE\.ssh\known_hosts
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git clone git@github.com:${{ github.repository }}.git ./
          Get-ChildItem .

      # - name: Checkout repo With SSH On Windows
      #   uses: lgf4591/CheckoutWithSSHAction@main
      #   with:
      #     # repo: lgf4591/codespaces-actions-playground
      #     git_private_key: ${{ secrets.ACTION_KEY }}
      #     shell: powershell
      #     # branch: main
      
      # - name: SSH test
      #   run: |
      #     cat  $env:USERPROFILE\.ssh\id_rsa
      #     ssh -T git@github.com